import type { IconifyIcon } from "@iconify/react";

const iconGroupLoaders = {
  "flat-color-icons": () => import("./icons/flat-color-icons"),
  logos: () => import("./icons/logos"),
  lucide: () => import("./icons/lucide"),
  mdi: () => import("./icons/mdi"),
  "simple-icons": () => import("./icons/simple-icons"),
  tabler: () => import("./icons/tabler"),
  uil: () => import("./icons/uil"),
} satisfies Record<
  string,
  () => Promise<{ icons: Readonly<Record<string, IconifyIcon>> }>
>;

const bundledIconNames = new Set([
  "flat-color-icons:advertising",
  "flat-color-icons:bookmark",
  "flat-color-icons:bullish",
  "flat-color-icons:collaboration",
  "flat-color-icons:combo-chart",
  "flat-color-icons:conference-call",
  "flat-color-icons:contacts",
  "flat-color-icons:currency-exchange",
  "flat-color-icons:data-protection",
  "flat-color-icons:debt",
  "flat-color-icons:document",
  "flat-color-icons:donate",
  "flat-color-icons:electrical-sensor",
  "flat-color-icons:feedback",
  "flat-color-icons:globe",
  "flat-color-icons:lock-portrait",
  "flat-color-icons:mind-map",
  "flat-color-icons:overtime",
  "flat-color-icons:refresh",
  "flat-color-icons:ruler",
  "flat-color-icons:sales-performance",
  "flat-color-icons:services",
  "flat-color-icons:shop",
  "flat-color-icons:sms",
  "flat-color-icons:statistics",
  "flat-color-icons:todo-list",
  "flat-color-icons:unlock",
  "flat-color-icons:workflow",
  "logos:apple",
  "logos:facebook",
  "logos:github",
  "logos:google",
  "logos:google-icon",
  "logos:mailgun-icon",
  "logos:telegram",
  "lucide:chevron-right",
  "mdi:access-time",
  "mdi:account",
  "mdi:account-multiple-plus-outline",
  "mdi:account-plus-outline",
  "mdi:apple",
  "mdi:cancel",
  "mdi:chevron-down",
  "mdi:chevron-right",
  "mdi:clock-time-eight",
  "mdi:cog",
  "mdi:content-copy",
  "mdi:currency-usd",
  "mdi:database-plus",
  "mdi:delete-sweep",
  "mdi:devices",
  "mdi:dice-multiple",
  "mdi:download",
  "mdi:email-multiple",
  "mdi:email-outline",
  "mdi:email-send",
  "mdi:eye",
  "mdi:facebook",
  "mdi:file-document-outline",
  "mdi:gift",
  "mdi:github",
  "mdi:google",
  "mdi:help-circle-outline",
  "mdi:key",
  "mdi:loading",
  "mdi:message-text-clock-outline",
  "mdi:microsoft-windows",
  "mdi:open-in-new",
  "mdi:phone-settings",
  "mdi:resistor-nodes",
  "mdi:server",
  "mdi:shield-account-outline",
  "mdi:shield-check-outline",
  "mdi:success-circle-outline",
  "mdi:telegram",
  "mdi:telephone",
  "mdi:tune-variant",
  "mdi:web",
  "simple-icons:harmonyos",
  "simple-icons:ios",
  "tabler:external-link",
  "uil:android",
  "uil:apple",
  "uil:bell",
  "uil:book-alt",
  "uil:check",
  "uil:clipboard-notes",
  "uil:cloud-data-connection",
  "uil:copy",
  "uil:dashboard",
  "uil:database",
  "uil:discord",
  "uil:envelope",
  "uil:exchange-alt",
  "uil:exit",
  "uil:facebook",
  "uil:github",
  "uil:image-upload",
  "uil:instagram",
  "uil:linkedin",
  "uil:linux",
  "uil:loading",
  "uil:megaphone",
  "uil:message",
  "uil:navigator",
  "uil:notes",
  "uil:refresh",
  "uil:server",
  "uil:server-network",
  "uil:servers",
  "uil:shield-check",
  "uil:shield-exclamation",
  "uil:shop",
  "uil:sync",
  "uil:telegram",
  "uil:twitter",
  "uil:user",
  "uil:users-alt",
  "uil:wallet",
]);

export function isBundledIcon(name: string) {
  return bundledIconNames.has(name);
}

export async function loadBundledIcon(name: string) {
  if (!isBundledIcon(name)) {
    return;
  }

  const [prefix, iconName] = name.split(":");
  const loader = iconGroupLoaders[prefix as keyof typeof iconGroupLoaders];
  const module = await loader();
  return module.icons[iconName ?? ""];
}
