/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'

const IndexLazyRouteImport = createFileRoute('/')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const DashboardWithdrawalLazyRouteImport = createFileRoute(
  '/dashboard/withdrawal',
)()
const DashboardNodesLazyRouteImport = createFileRoute('/dashboard/nodes')()
const DashboardServersRouteLazyRouteImport =
  createFileRoute('/dashboard/servers')()
const DashboardProductRouteLazyRouteImport =
  createFileRoute('/dashboard/product')()
const DashboardLogRouteLazyRouteImport = createFileRoute('/dashboard/log')()
const DashboardUserIndexLazyRouteImport = createFileRoute('/dashboard/user/')()
const DashboardTicketIndexLazyRouteImport =
  createFileRoute('/dashboard/ticket/')()
const DashboardSystemIndexLazyRouteImport =
  createFileRoute('/dashboard/system/')()
const DashboardSubscribeIndexLazyRouteImport = createFileRoute(
  '/dashboard/subscribe/',
)()
const DashboardServersIndexLazyRouteImport = createFileRoute(
  '/dashboard/servers/',
)()
const DashboardProductIndexLazyRouteImport = createFileRoute(
  '/dashboard/product/',
)()
const DashboardPaymentIndexLazyRouteImport = createFileRoute(
  '/dashboard/payment/',
)()
const DashboardOrderIndexLazyRouteImport =
  createFileRoute('/dashboard/order/')()
const DashboardMarketingIndexLazyRouteImport = createFileRoute(
  '/dashboard/marketing/',
)()
const DashboardDocumentIndexLazyRouteImport = createFileRoute(
  '/dashboard/document/',
)()
const DashboardCouponIndexLazyRouteImport =
  createFileRoute('/dashboard/coupon/')()
const DashboardAuthControlIndexLazyRouteImport = createFileRoute(
  '/dashboard/auth-control/',
)()
const DashboardAnnouncementIndexLazyRouteImport = createFileRoute(
  '/dashboard/announcement/',
)()
const DashboardAdsIndexLazyRouteImport = createFileRoute('/dashboard/ads/')()
const DashboardServersNewLazyRouteImport = createFileRoute(
  '/dashboard/servers/new',
)()
const DashboardServersServerIdLazyRouteImport = createFileRoute(
  '/dashboard/servers/$serverId',
)()
const DashboardProductProductIdLazyRouteImport = createFileRoute(
  '/dashboard/product/$productId',
)()
const DashboardLogTrafficDetailsLazyRouteImport = createFileRoute(
  '/dashboard/log/traffic-details',
)()
const DashboardLogSubscribeTrafficLazyRouteImport = createFileRoute(
  '/dashboard/log/subscribe-traffic',
)()
const DashboardLogSubscribeLazyRouteImport = createFileRoute(
  '/dashboard/log/subscribe',
)()
const DashboardLogServerTrafficLazyRouteImport = createFileRoute(
  '/dashboard/log/server-traffic',
)()
const DashboardLogResetSubscribeLazyRouteImport = createFileRoute(
  '/dashboard/log/reset-subscribe',
)()
const DashboardLogRegisterLazyRouteImport = createFileRoute(
  '/dashboard/log/register',
)()
const DashboardLogOrderLazyRouteImport = createFileRoute(
  '/dashboard/log/order',
)()
const DashboardLogMobileLazyRouteImport = createFileRoute(
  '/dashboard/log/mobile',
)()
const DashboardLogLoginLazyRouteImport = createFileRoute(
  '/dashboard/log/login',
)()
const DashboardLogGiftLazyRouteImport = createFileRoute('/dashboard/log/gift')()
const DashboardLogEmailLazyRouteImport = createFileRoute(
  '/dashboard/log/email',
)()
const DashboardLogCommissionLazyRouteImport = createFileRoute(
  '/dashboard/log/commission',
)()
const DashboardLogBalanceLazyRouteImport = createFileRoute(
  '/dashboard/log/balance',
)()

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/dashboard/route.lazy').then((d) => d.Route),
)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardWithdrawalLazyRoute = DashboardWithdrawalLazyRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard/withdrawal.lazy').then((d) => d.Route),
)
const DashboardNodesLazyRoute = DashboardNodesLazyRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard/nodes.lazy').then((d) => d.Route),
)
const DashboardServersRouteLazyRoute =
  DashboardServersRouteLazyRouteImport.update({
    id: '/servers',
    path: '/servers',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/servers/route.lazy').then((d) => d.Route),
  )
const DashboardProductRouteLazyRoute =
  DashboardProductRouteLazyRouteImport.update({
    id: '/product',
    path: '/product',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/product/route.lazy').then((d) => d.Route),
  )
const DashboardLogRouteLazyRoute = DashboardLogRouteLazyRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/route.lazy').then((d) => d.Route),
)
const DashboardUserIndexLazyRoute = DashboardUserIndexLazyRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard/user/index.lazy').then((d) => d.Route),
)
const DashboardTicketIndexLazyRoute =
  DashboardTicketIndexLazyRouteImport.update({
    id: '/ticket/',
    path: '/ticket/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/ticket/index.lazy').then((d) => d.Route),
  )
const DashboardSystemIndexLazyRoute =
  DashboardSystemIndexLazyRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/system/index.lazy').then((d) => d.Route),
  )
const DashboardSubscribeIndexLazyRoute =
  DashboardSubscribeIndexLazyRouteImport.update({
    id: '/subscribe/',
    path: '/subscribe/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/subscribe/index.lazy').then((d) => d.Route),
  )
const DashboardServersIndexLazyRoute =
  DashboardServersIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardServersRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/servers/index.lazy').then((d) => d.Route),
  )
const DashboardProductIndexLazyRoute =
  DashboardProductIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProductRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/product/index.lazy').then((d) => d.Route),
  )
const DashboardPaymentIndexLazyRoute =
  DashboardPaymentIndexLazyRouteImport.update({
    id: '/payment/',
    path: '/payment/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/payment/index.lazy').then((d) => d.Route),
  )
const DashboardOrderIndexLazyRoute = DashboardOrderIndexLazyRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard/order/index.lazy').then((d) => d.Route),
)
const DashboardMarketingIndexLazyRoute =
  DashboardMarketingIndexLazyRouteImport.update({
    id: '/marketing/',
    path: '/marketing/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/marketing/index.lazy').then((d) => d.Route),
  )
const DashboardDocumentIndexLazyRoute =
  DashboardDocumentIndexLazyRouteImport.update({
    id: '/document/',
    path: '/document/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/document/index.lazy').then((d) => d.Route),
  )
const DashboardCouponIndexLazyRoute =
  DashboardCouponIndexLazyRouteImport.update({
    id: '/coupon/',
    path: '/coupon/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/coupon/index.lazy').then((d) => d.Route),
  )
const DashboardAuthControlIndexLazyRoute =
  DashboardAuthControlIndexLazyRouteImport.update({
    id: '/auth-control/',
    path: '/auth-control/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/auth-control/index.lazy').then((d) => d.Route),
  )
const DashboardAnnouncementIndexLazyRoute =
  DashboardAnnouncementIndexLazyRouteImport.update({
    id: '/announcement/',
    path: '/announcement/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/announcement/index.lazy').then((d) => d.Route),
  )
const DashboardAdsIndexLazyRoute = DashboardAdsIndexLazyRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard/ads/index.lazy').then((d) => d.Route),
)
const DashboardServersNewLazyRoute = DashboardServersNewLazyRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardServersRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/servers/new.lazy').then((d) => d.Route),
)
const DashboardServersServerIdLazyRoute =
  DashboardServersServerIdLazyRouteImport.update({
    id: '/$serverId',
    path: '/$serverId',
    getParentRoute: () => DashboardServersRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/servers/$serverId.lazy').then((d) => d.Route),
  )
const DashboardProductProductIdLazyRoute =
  DashboardProductProductIdLazyRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => DashboardProductRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/product/$productId.lazy').then((d) => d.Route),
  )
const DashboardLogTrafficDetailsLazyRoute =
  DashboardLogTrafficDetailsLazyRouteImport.update({
    id: '/traffic-details',
    path: '/traffic-details',
    getParentRoute: () => DashboardLogRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/traffic-details.lazy').then((d) => d.Route),
  )
const DashboardLogSubscribeTrafficLazyRoute =
  DashboardLogSubscribeTrafficLazyRouteImport.update({
    id: '/subscribe-traffic',
    path: '/subscribe-traffic',
    getParentRoute: () => DashboardLogRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/subscribe-traffic.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardLogSubscribeLazyRoute =
  DashboardLogSubscribeLazyRouteImport.update({
    id: '/subscribe',
    path: '/subscribe',
    getParentRoute: () => DashboardLogRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/subscribe.lazy').then((d) => d.Route),
  )
const DashboardLogServerTrafficLazyRoute =
  DashboardLogServerTrafficLazyRouteImport.update({
    id: '/server-traffic',
    path: '/server-traffic',
    getParentRoute: () => DashboardLogRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/server-traffic.lazy').then((d) => d.Route),
  )
const DashboardLogResetSubscribeLazyRoute =
  DashboardLogResetSubscribeLazyRouteImport.update({
    id: '/reset-subscribe',
    path: '/reset-subscribe',
    getParentRoute: () => DashboardLogRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/reset-subscribe.lazy').then((d) => d.Route),
  )
const DashboardLogRegisterLazyRoute =
  DashboardLogRegisterLazyRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => DashboardLogRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/register.lazy').then((d) => d.Route),
  )
const DashboardLogOrderLazyRoute = DashboardLogOrderLazyRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => DashboardLogRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/order.lazy').then((d) => d.Route),
)
const DashboardLogMobileLazyRoute = DashboardLogMobileLazyRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => DashboardLogRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/mobile.lazy').then((d) => d.Route),
)
const DashboardLogLoginLazyRoute = DashboardLogLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardLogRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/login.lazy').then((d) => d.Route),
)
const DashboardLogGiftLazyRoute = DashboardLogGiftLazyRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => DashboardLogRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/gift.lazy').then((d) => d.Route),
)
const DashboardLogEmailLazyRoute = DashboardLogEmailLazyRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => DashboardLogRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/email.lazy').then((d) => d.Route),
)
const DashboardLogCommissionLazyRoute =
  DashboardLogCommissionLazyRouteImport.update({
    id: '/commission',
    path: '/commission',
    getParentRoute: () => DashboardLogRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/log/commission.lazy').then((d) => d.Route),
  )
const DashboardLogBalanceLazyRoute = DashboardLogBalanceLazyRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => DashboardLogRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/log/balance.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/log': typeof DashboardLogRouteLazyRouteWithChildren
  '/dashboard/product': typeof DashboardProductRouteLazyRouteWithChildren
  '/dashboard/servers': typeof DashboardServersRouteLazyRouteWithChildren
  '/dashboard/nodes': typeof DashboardNodesLazyRoute
  '/dashboard/withdrawal': typeof DashboardWithdrawalLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/log/balance': typeof DashboardLogBalanceLazyRoute
  '/dashboard/log/commission': typeof DashboardLogCommissionLazyRoute
  '/dashboard/log/email': typeof DashboardLogEmailLazyRoute
  '/dashboard/log/gift': typeof DashboardLogGiftLazyRoute
  '/dashboard/log/login': typeof DashboardLogLoginLazyRoute
  '/dashboard/log/mobile': typeof DashboardLogMobileLazyRoute
  '/dashboard/log/order': typeof DashboardLogOrderLazyRoute
  '/dashboard/log/register': typeof DashboardLogRegisterLazyRoute
  '/dashboard/log/reset-subscribe': typeof DashboardLogResetSubscribeLazyRoute
  '/dashboard/log/server-traffic': typeof DashboardLogServerTrafficLazyRoute
  '/dashboard/log/subscribe': typeof DashboardLogSubscribeLazyRoute
  '/dashboard/log/subscribe-traffic': typeof DashboardLogSubscribeTrafficLazyRoute
  '/dashboard/log/traffic-details': typeof DashboardLogTrafficDetailsLazyRoute
  '/dashboard/product/$productId': typeof DashboardProductProductIdLazyRoute
  '/dashboard/servers/$serverId': typeof DashboardServersServerIdLazyRoute
  '/dashboard/servers/new': typeof DashboardServersNewLazyRoute
  '/dashboard/ads': typeof DashboardAdsIndexLazyRoute
  '/dashboard/announcement': typeof DashboardAnnouncementIndexLazyRoute
  '/dashboard/auth-control': typeof DashboardAuthControlIndexLazyRoute
  '/dashboard/coupon': typeof DashboardCouponIndexLazyRoute
  '/dashboard/document': typeof DashboardDocumentIndexLazyRoute
  '/dashboard/marketing': typeof DashboardMarketingIndexLazyRoute
  '/dashboard/order': typeof DashboardOrderIndexLazyRoute
  '/dashboard/payment': typeof DashboardPaymentIndexLazyRoute
  '/dashboard/product/': typeof DashboardProductIndexLazyRoute
  '/dashboard/servers/': typeof DashboardServersIndexLazyRoute
  '/dashboard/subscribe': typeof DashboardSubscribeIndexLazyRoute
  '/dashboard/system': typeof DashboardSystemIndexLazyRoute
  '/dashboard/ticket': typeof DashboardTicketIndexLazyRoute
  '/dashboard/user': typeof DashboardUserIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dashboard/log': typeof DashboardLogRouteLazyRouteWithChildren
  '/dashboard/nodes': typeof DashboardNodesLazyRoute
  '/dashboard/withdrawal': typeof DashboardWithdrawalLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/log/balance': typeof DashboardLogBalanceLazyRoute
  '/dashboard/log/commission': typeof DashboardLogCommissionLazyRoute
  '/dashboard/log/email': typeof DashboardLogEmailLazyRoute
  '/dashboard/log/gift': typeof DashboardLogGiftLazyRoute
  '/dashboard/log/login': typeof DashboardLogLoginLazyRoute
  '/dashboard/log/mobile': typeof DashboardLogMobileLazyRoute
  '/dashboard/log/order': typeof DashboardLogOrderLazyRoute
  '/dashboard/log/register': typeof DashboardLogRegisterLazyRoute
  '/dashboard/log/reset-subscribe': typeof DashboardLogResetSubscribeLazyRoute
  '/dashboard/log/server-traffic': typeof DashboardLogServerTrafficLazyRoute
  '/dashboard/log/subscribe': typeof DashboardLogSubscribeLazyRoute
  '/dashboard/log/subscribe-traffic': typeof DashboardLogSubscribeTrafficLazyRoute
  '/dashboard/log/traffic-details': typeof DashboardLogTrafficDetailsLazyRoute
  '/dashboard/product/$productId': typeof DashboardProductProductIdLazyRoute
  '/dashboard/servers/$serverId': typeof DashboardServersServerIdLazyRoute
  '/dashboard/servers/new': typeof DashboardServersNewLazyRoute
  '/dashboard/ads': typeof DashboardAdsIndexLazyRoute
  '/dashboard/announcement': typeof DashboardAnnouncementIndexLazyRoute
  '/dashboard/auth-control': typeof DashboardAuthControlIndexLazyRoute
  '/dashboard/coupon': typeof DashboardCouponIndexLazyRoute
  '/dashboard/document': typeof DashboardDocumentIndexLazyRoute
  '/dashboard/marketing': typeof DashboardMarketingIndexLazyRoute
  '/dashboard/order': typeof DashboardOrderIndexLazyRoute
  '/dashboard/payment': typeof DashboardPaymentIndexLazyRoute
  '/dashboard/product': typeof DashboardProductIndexLazyRoute
  '/dashboard/servers': typeof DashboardServersIndexLazyRoute
  '/dashboard/subscribe': typeof DashboardSubscribeIndexLazyRoute
  '/dashboard/system': typeof DashboardSystemIndexLazyRoute
  '/dashboard/ticket': typeof DashboardTicketIndexLazyRoute
  '/dashboard/user': typeof DashboardUserIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/log': typeof DashboardLogRouteLazyRouteWithChildren
  '/dashboard/product': typeof DashboardProductRouteLazyRouteWithChildren
  '/dashboard/servers': typeof DashboardServersRouteLazyRouteWithChildren
  '/dashboard/nodes': typeof DashboardNodesLazyRoute
  '/dashboard/withdrawal': typeof DashboardWithdrawalLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/log/balance': typeof DashboardLogBalanceLazyRoute
  '/dashboard/log/commission': typeof DashboardLogCommissionLazyRoute
  '/dashboard/log/email': typeof DashboardLogEmailLazyRoute
  '/dashboard/log/gift': typeof DashboardLogGiftLazyRoute
  '/dashboard/log/login': typeof DashboardLogLoginLazyRoute
  '/dashboard/log/mobile': typeof DashboardLogMobileLazyRoute
  '/dashboard/log/order': typeof DashboardLogOrderLazyRoute
  '/dashboard/log/register': typeof DashboardLogRegisterLazyRoute
  '/dashboard/log/reset-subscribe': typeof DashboardLogResetSubscribeLazyRoute
  '/dashboard/log/server-traffic': typeof DashboardLogServerTrafficLazyRoute
  '/dashboard/log/subscribe': typeof DashboardLogSubscribeLazyRoute
  '/dashboard/log/subscribe-traffic': typeof DashboardLogSubscribeTrafficLazyRoute
  '/dashboard/log/traffic-details': typeof DashboardLogTrafficDetailsLazyRoute
  '/dashboard/product/$productId': typeof DashboardProductProductIdLazyRoute
  '/dashboard/servers/$serverId': typeof DashboardServersServerIdLazyRoute
  '/dashboard/servers/new': typeof DashboardServersNewLazyRoute
  '/dashboard/ads/': typeof DashboardAdsIndexLazyRoute
  '/dashboard/announcement/': typeof DashboardAnnouncementIndexLazyRoute
  '/dashboard/auth-control/': typeof DashboardAuthControlIndexLazyRoute
  '/dashboard/coupon/': typeof DashboardCouponIndexLazyRoute
  '/dashboard/document/': typeof DashboardDocumentIndexLazyRoute
  '/dashboard/marketing/': typeof DashboardMarketingIndexLazyRoute
  '/dashboard/order/': typeof DashboardOrderIndexLazyRoute
  '/dashboard/payment/': typeof DashboardPaymentIndexLazyRoute
  '/dashboard/product/': typeof DashboardProductIndexLazyRoute
  '/dashboard/servers/': typeof DashboardServersIndexLazyRoute
  '/dashboard/subscribe/': typeof DashboardSubscribeIndexLazyRoute
  '/dashboard/system/': typeof DashboardSystemIndexLazyRoute
  '/dashboard/ticket/': typeof DashboardTicketIndexLazyRoute
  '/dashboard/user/': typeof DashboardUserIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/log'
    | '/dashboard/product'
    | '/dashboard/servers'
    | '/dashboard/nodes'
    | '/dashboard/withdrawal'
    | '/dashboard/'
    | '/dashboard/log/balance'
    | '/dashboard/log/commission'
    | '/dashboard/log/email'
    | '/dashboard/log/gift'
    | '/dashboard/log/login'
    | '/dashboard/log/mobile'
    | '/dashboard/log/order'
    | '/dashboard/log/register'
    | '/dashboard/log/reset-subscribe'
    | '/dashboard/log/server-traffic'
    | '/dashboard/log/subscribe'
    | '/dashboard/log/subscribe-traffic'
    | '/dashboard/log/traffic-details'
    | '/dashboard/product/$productId'
    | '/dashboard/servers/$serverId'
    | '/dashboard/servers/new'
    | '/dashboard/ads'
    | '/dashboard/announcement'
    | '/dashboard/auth-control'
    | '/dashboard/coupon'
    | '/dashboard/document'
    | '/dashboard/marketing'
    | '/dashboard/order'
    | '/dashboard/payment'
    | '/dashboard/product/'
    | '/dashboard/servers/'
    | '/dashboard/subscribe'
    | '/dashboard/system'
    | '/dashboard/ticket'
    | '/dashboard/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/log'
    | '/dashboard/nodes'
    | '/dashboard/withdrawal'
    | '/dashboard'
    | '/dashboard/log/balance'
    | '/dashboard/log/commission'
    | '/dashboard/log/email'
    | '/dashboard/log/gift'
    | '/dashboard/log/login'
    | '/dashboard/log/mobile'
    | '/dashboard/log/order'
    | '/dashboard/log/register'
    | '/dashboard/log/reset-subscribe'
    | '/dashboard/log/server-traffic'
    | '/dashboard/log/subscribe'
    | '/dashboard/log/subscribe-traffic'
    | '/dashboard/log/traffic-details'
    | '/dashboard/product/$productId'
    | '/dashboard/servers/$serverId'
    | '/dashboard/servers/new'
    | '/dashboard/ads'
    | '/dashboard/announcement'
    | '/dashboard/auth-control'
    | '/dashboard/coupon'
    | '/dashboard/document'
    | '/dashboard/marketing'
    | '/dashboard/order'
    | '/dashboard/payment'
    | '/dashboard/product'
    | '/dashboard/servers'
    | '/dashboard/subscribe'
    | '/dashboard/system'
    | '/dashboard/ticket'
    | '/dashboard/user'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/log'
    | '/dashboard/product'
    | '/dashboard/servers'
    | '/dashboard/nodes'
    | '/dashboard/withdrawal'
    | '/dashboard/'
    | '/dashboard/log/balance'
    | '/dashboard/log/commission'
    | '/dashboard/log/email'
    | '/dashboard/log/gift'
    | '/dashboard/log/login'
    | '/dashboard/log/mobile'
    | '/dashboard/log/order'
    | '/dashboard/log/register'
    | '/dashboard/log/reset-subscribe'
    | '/dashboard/log/server-traffic'
    | '/dashboard/log/subscribe'
    | '/dashboard/log/subscribe-traffic'
    | '/dashboard/log/traffic-details'
    | '/dashboard/product/$productId'
    | '/dashboard/servers/$serverId'
    | '/dashboard/servers/new'
    | '/dashboard/ads/'
    | '/dashboard/announcement/'
    | '/dashboard/auth-control/'
    | '/dashboard/coupon/'
    | '/dashboard/document/'
    | '/dashboard/marketing/'
    | '/dashboard/order/'
    | '/dashboard/payment/'
    | '/dashboard/product/'
    | '/dashboard/servers/'
    | '/dashboard/subscribe/'
    | '/dashboard/system/'
    | '/dashboard/ticket/'
    | '/dashboard/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/withdrawal': {
      id: '/dashboard/withdrawal'
      path: '/withdrawal'
      fullPath: '/dashboard/withdrawal'
      preLoaderRoute: typeof DashboardWithdrawalLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nodes': {
      id: '/dashboard/nodes'
      path: '/nodes'
      fullPath: '/dashboard/nodes'
      preLoaderRoute: typeof DashboardNodesLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/servers': {
      id: '/dashboard/servers'
      path: '/servers'
      fullPath: '/dashboard/servers'
      preLoaderRoute: typeof DashboardServersRouteLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product': {
      id: '/dashboard/product'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardProductRouteLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/log': {
      id: '/dashboard/log'
      path: '/log'
      fullPath: '/dashboard/log'
      preLoaderRoute: typeof DashboardLogRouteLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/user/': {
      id: '/dashboard/user/'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ticket/': {
      id: '/dashboard/ticket/'
      path: '/ticket'
      fullPath: '/dashboard/ticket'
      preLoaderRoute: typeof DashboardTicketIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/system/': {
      id: '/dashboard/system/'
      path: '/system'
      fullPath: '/dashboard/system'
      preLoaderRoute: typeof DashboardSystemIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/subscribe/': {
      id: '/dashboard/subscribe/'
      path: '/subscribe'
      fullPath: '/dashboard/subscribe'
      preLoaderRoute: typeof DashboardSubscribeIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/servers/': {
      id: '/dashboard/servers/'
      path: '/'
      fullPath: '/dashboard/servers/'
      preLoaderRoute: typeof DashboardServersIndexLazyRouteImport
      parentRoute: typeof DashboardServersRouteLazyRoute
    }
    '/dashboard/product/': {
      id: '/dashboard/product/'
      path: '/'
      fullPath: '/dashboard/product/'
      preLoaderRoute: typeof DashboardProductIndexLazyRouteImport
      parentRoute: typeof DashboardProductRouteLazyRoute
    }
    '/dashboard/payment/': {
      id: '/dashboard/payment/'
      path: '/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof DashboardPaymentIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/order/': {
      id: '/dashboard/order/'
      path: '/order'
      fullPath: '/dashboard/order'
      preLoaderRoute: typeof DashboardOrderIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/marketing/': {
      id: '/dashboard/marketing/'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/document/': {
      id: '/dashboard/document/'
      path: '/document'
      fullPath: '/dashboard/document'
      preLoaderRoute: typeof DashboardDocumentIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/coupon/': {
      id: '/dashboard/coupon/'
      path: '/coupon'
      fullPath: '/dashboard/coupon'
      preLoaderRoute: typeof DashboardCouponIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/auth-control/': {
      id: '/dashboard/auth-control/'
      path: '/auth-control'
      fullPath: '/dashboard/auth-control'
      preLoaderRoute: typeof DashboardAuthControlIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/announcement/': {
      id: '/dashboard/announcement/'
      path: '/announcement'
      fullPath: '/dashboard/announcement'
      preLoaderRoute: typeof DashboardAnnouncementIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ads/': {
      id: '/dashboard/ads/'
      path: '/ads'
      fullPath: '/dashboard/ads'
      preLoaderRoute: typeof DashboardAdsIndexLazyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/servers/new': {
      id: '/dashboard/servers/new'
      path: '/new'
      fullPath: '/dashboard/servers/new'
      preLoaderRoute: typeof DashboardServersNewLazyRouteImport
      parentRoute: typeof DashboardServersRouteLazyRoute
    }
    '/dashboard/servers/$serverId': {
      id: '/dashboard/servers/$serverId'
      path: '/$serverId'
      fullPath: '/dashboard/servers/$serverId'
      preLoaderRoute: typeof DashboardServersServerIdLazyRouteImport
      parentRoute: typeof DashboardServersRouteLazyRoute
    }
    '/dashboard/product/$productId': {
      id: '/dashboard/product/$productId'
      path: '/$productId'
      fullPath: '/dashboard/product/$productId'
      preLoaderRoute: typeof DashboardProductProductIdLazyRouteImport
      parentRoute: typeof DashboardProductRouteLazyRoute
    }
    '/dashboard/log/traffic-details': {
      id: '/dashboard/log/traffic-details'
      path: '/traffic-details'
      fullPath: '/dashboard/log/traffic-details'
      preLoaderRoute: typeof DashboardLogTrafficDetailsLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/subscribe-traffic': {
      id: '/dashboard/log/subscribe-traffic'
      path: '/subscribe-traffic'
      fullPath: '/dashboard/log/subscribe-traffic'
      preLoaderRoute: typeof DashboardLogSubscribeTrafficLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/subscribe': {
      id: '/dashboard/log/subscribe'
      path: '/subscribe'
      fullPath: '/dashboard/log/subscribe'
      preLoaderRoute: typeof DashboardLogSubscribeLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/server-traffic': {
      id: '/dashboard/log/server-traffic'
      path: '/server-traffic'
      fullPath: '/dashboard/log/server-traffic'
      preLoaderRoute: typeof DashboardLogServerTrafficLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/reset-subscribe': {
      id: '/dashboard/log/reset-subscribe'
      path: '/reset-subscribe'
      fullPath: '/dashboard/log/reset-subscribe'
      preLoaderRoute: typeof DashboardLogResetSubscribeLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/register': {
      id: '/dashboard/log/register'
      path: '/register'
      fullPath: '/dashboard/log/register'
      preLoaderRoute: typeof DashboardLogRegisterLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/order': {
      id: '/dashboard/log/order'
      path: '/order'
      fullPath: '/dashboard/log/order'
      preLoaderRoute: typeof DashboardLogOrderLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/mobile': {
      id: '/dashboard/log/mobile'
      path: '/mobile'
      fullPath: '/dashboard/log/mobile'
      preLoaderRoute: typeof DashboardLogMobileLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/login': {
      id: '/dashboard/log/login'
      path: '/login'
      fullPath: '/dashboard/log/login'
      preLoaderRoute: typeof DashboardLogLoginLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/gift': {
      id: '/dashboard/log/gift'
      path: '/gift'
      fullPath: '/dashboard/log/gift'
      preLoaderRoute: typeof DashboardLogGiftLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/email': {
      id: '/dashboard/log/email'
      path: '/email'
      fullPath: '/dashboard/log/email'
      preLoaderRoute: typeof DashboardLogEmailLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/commission': {
      id: '/dashboard/log/commission'
      path: '/commission'
      fullPath: '/dashboard/log/commission'
      preLoaderRoute: typeof DashboardLogCommissionLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
    '/dashboard/log/balance': {
      id: '/dashboard/log/balance'
      path: '/balance'
      fullPath: '/dashboard/log/balance'
      preLoaderRoute: typeof DashboardLogBalanceLazyRouteImport
      parentRoute: typeof DashboardLogRouteLazyRoute
    }
  }
}

interface DashboardLogRouteLazyRouteChildren {
  DashboardLogBalanceLazyRoute: typeof DashboardLogBalanceLazyRoute
  DashboardLogCommissionLazyRoute: typeof DashboardLogCommissionLazyRoute
  DashboardLogEmailLazyRoute: typeof DashboardLogEmailLazyRoute
  DashboardLogGiftLazyRoute: typeof DashboardLogGiftLazyRoute
  DashboardLogLoginLazyRoute: typeof DashboardLogLoginLazyRoute
  DashboardLogMobileLazyRoute: typeof DashboardLogMobileLazyRoute
  DashboardLogOrderLazyRoute: typeof DashboardLogOrderLazyRoute
  DashboardLogRegisterLazyRoute: typeof DashboardLogRegisterLazyRoute
  DashboardLogResetSubscribeLazyRoute: typeof DashboardLogResetSubscribeLazyRoute
  DashboardLogServerTrafficLazyRoute: typeof DashboardLogServerTrafficLazyRoute
  DashboardLogSubscribeLazyRoute: typeof DashboardLogSubscribeLazyRoute
  DashboardLogSubscribeTrafficLazyRoute: typeof DashboardLogSubscribeTrafficLazyRoute
  DashboardLogTrafficDetailsLazyRoute: typeof DashboardLogTrafficDetailsLazyRoute
}

const DashboardLogRouteLazyRouteChildren: DashboardLogRouteLazyRouteChildren = {
  DashboardLogBalanceLazyRoute: DashboardLogBalanceLazyRoute,
  DashboardLogCommissionLazyRoute: DashboardLogCommissionLazyRoute,
  DashboardLogEmailLazyRoute: DashboardLogEmailLazyRoute,
  DashboardLogGiftLazyRoute: DashboardLogGiftLazyRoute,
  DashboardLogLoginLazyRoute: DashboardLogLoginLazyRoute,
  DashboardLogMobileLazyRoute: DashboardLogMobileLazyRoute,
  DashboardLogOrderLazyRoute: DashboardLogOrderLazyRoute,
  DashboardLogRegisterLazyRoute: DashboardLogRegisterLazyRoute,
  DashboardLogResetSubscribeLazyRoute: DashboardLogResetSubscribeLazyRoute,
  DashboardLogServerTrafficLazyRoute: DashboardLogServerTrafficLazyRoute,
  DashboardLogSubscribeLazyRoute: DashboardLogSubscribeLazyRoute,
  DashboardLogSubscribeTrafficLazyRoute: DashboardLogSubscribeTrafficLazyRoute,
  DashboardLogTrafficDetailsLazyRoute: DashboardLogTrafficDetailsLazyRoute,
}

const DashboardLogRouteLazyRouteWithChildren =
  DashboardLogRouteLazyRoute._addFileChildren(
    DashboardLogRouteLazyRouteChildren,
  )

interface DashboardProductRouteLazyRouteChildren {
  DashboardProductProductIdLazyRoute: typeof DashboardProductProductIdLazyRoute
  DashboardProductIndexLazyRoute: typeof DashboardProductIndexLazyRoute
}

const DashboardProductRouteLazyRouteChildren: DashboardProductRouteLazyRouteChildren =
  {
    DashboardProductProductIdLazyRoute: DashboardProductProductIdLazyRoute,
    DashboardProductIndexLazyRoute: DashboardProductIndexLazyRoute,
  }

const DashboardProductRouteLazyRouteWithChildren =
  DashboardProductRouteLazyRoute._addFileChildren(
    DashboardProductRouteLazyRouteChildren,
  )

interface DashboardServersRouteLazyRouteChildren {
  DashboardServersServerIdLazyRoute: typeof DashboardServersServerIdLazyRoute
  DashboardServersNewLazyRoute: typeof DashboardServersNewLazyRoute
  DashboardServersIndexLazyRoute: typeof DashboardServersIndexLazyRoute
}

const DashboardServersRouteLazyRouteChildren: DashboardServersRouteLazyRouteChildren =
  {
    DashboardServersServerIdLazyRoute: DashboardServersServerIdLazyRoute,
    DashboardServersNewLazyRoute: DashboardServersNewLazyRoute,
    DashboardServersIndexLazyRoute: DashboardServersIndexLazyRoute,
  }

const DashboardServersRouteLazyRouteWithChildren =
  DashboardServersRouteLazyRoute._addFileChildren(
    DashboardServersRouteLazyRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardLogRouteLazyRoute: typeof DashboardLogRouteLazyRouteWithChildren
  DashboardProductRouteLazyRoute: typeof DashboardProductRouteLazyRouteWithChildren
  DashboardServersRouteLazyRoute: typeof DashboardServersRouteLazyRouteWithChildren
  DashboardNodesLazyRoute: typeof DashboardNodesLazyRoute
  DashboardWithdrawalLazyRoute: typeof DashboardWithdrawalLazyRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardAdsIndexLazyRoute: typeof DashboardAdsIndexLazyRoute
  DashboardAnnouncementIndexLazyRoute: typeof DashboardAnnouncementIndexLazyRoute
  DashboardAuthControlIndexLazyRoute: typeof DashboardAuthControlIndexLazyRoute
  DashboardCouponIndexLazyRoute: typeof DashboardCouponIndexLazyRoute
  DashboardDocumentIndexLazyRoute: typeof DashboardDocumentIndexLazyRoute
  DashboardMarketingIndexLazyRoute: typeof DashboardMarketingIndexLazyRoute
  DashboardOrderIndexLazyRoute: typeof DashboardOrderIndexLazyRoute
  DashboardPaymentIndexLazyRoute: typeof DashboardPaymentIndexLazyRoute
  DashboardSubscribeIndexLazyRoute: typeof DashboardSubscribeIndexLazyRoute
  DashboardSystemIndexLazyRoute: typeof DashboardSystemIndexLazyRoute
  DashboardTicketIndexLazyRoute: typeof DashboardTicketIndexLazyRoute
  DashboardUserIndexLazyRoute: typeof DashboardUserIndexLazyRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLogRouteLazyRoute: DashboardLogRouteLazyRouteWithChildren,
  DashboardProductRouteLazyRoute: DashboardProductRouteLazyRouteWithChildren,
  DashboardServersRouteLazyRoute: DashboardServersRouteLazyRouteWithChildren,
  DashboardNodesLazyRoute: DashboardNodesLazyRoute,
  DashboardWithdrawalLazyRoute: DashboardWithdrawalLazyRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardAdsIndexLazyRoute: DashboardAdsIndexLazyRoute,
  DashboardAnnouncementIndexLazyRoute: DashboardAnnouncementIndexLazyRoute,
  DashboardAuthControlIndexLazyRoute: DashboardAuthControlIndexLazyRoute,
  DashboardCouponIndexLazyRoute: DashboardCouponIndexLazyRoute,
  DashboardDocumentIndexLazyRoute: DashboardDocumentIndexLazyRoute,
  DashboardMarketingIndexLazyRoute: DashboardMarketingIndexLazyRoute,
  DashboardOrderIndexLazyRoute: DashboardOrderIndexLazyRoute,
  DashboardPaymentIndexLazyRoute: DashboardPaymentIndexLazyRoute,
  DashboardSubscribeIndexLazyRoute: DashboardSubscribeIndexLazyRoute,
  DashboardSystemIndexLazyRoute: DashboardSystemIndexLazyRoute,
  DashboardTicketIndexLazyRoute: DashboardTicketIndexLazyRoute,
  DashboardUserIndexLazyRoute: DashboardUserIndexLazyRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
